version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: zinjvi/building-on-ci
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

  test1:
    executor: docker-publisher
    steps:
      - run:
          name: Test 1
          command: echo "test1"
  test2:
    executor: docker-publisher
    steps:
      - run:
          name: Test 2
          command: echo "test2"
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          context: docker-hub
          filters:
            branches:
              only: master
      - publish-latest:
          context: docker-hub
          requires:
            - build
          filters:
            branches:
              only: master

      - test1:
          requires:
            - build
          filters:
            branches:
              only: master
      - test2:
          requires:
            - build
            - publish-latest
            - test1
          filters:
            branches:
              only: master